spring.application.name=AI-Code-Reviewer
ai.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent
ai.api.key=AIzaSyD3n6yBkaaRzSTRgtdh8glAxMWMRahiDbs
server.port=9090